#:package YueYinqiu.Su.DotnetRunFileUtilities@0.0.3

using System.Text;
using CliWrap;

// requires UV_PUBLISH_TOKEN

var packageName = "csharp-like-file";

Console.WriteLine("Creating generator environment...");
var directory = Directory.CreateDirectory("generator");
directory.Delete(true);
var uv = Cli.Wrap("uv").WithWorkingDirectory(directory.FullName);
await uv.WithArguments(["init", "--managed-python"]).ExecuteAsync();

Console.WriteLine($"Installing {packageName}...");
await uv.WithArguments(["add", packageName]).ExecuteAsync();

Console.WriteLine($"Checking version...");
var output = new StringBuilder();
await (uv.WithArguments(["pip", "show", packageName]) | output).ExecuteAsync();
var packageVersion = output.ToString().Split("\n")
    .Where(x => x.StartsWith("Version: "))
    .Select(x => x["Version: ".Length..].Trim())
    .Single();

Console.WriteLine("Installing pyright...");
await uv.WithArguments(["add", "pyright"]).ExecuteAsync();

Console.WriteLine("Generating type stubs...");
await uv.WithArguments(["run", "pyright", "--createstub", packageName]).ExecuteAsync();
var generatedStubs = new DirectoryInfo(Path.Join(directory.FullName, "typings", packageName));

Console.WriteLine("Creating package environment...");
directory = Directory.CreateDirectory("package");
directory.Delete(true);
uv = Cli.Wrap("uv").WithWorkingDirectory(directory.FullName);

await File.WriteAllTextAsync(Path.GetFullPath("pyproject.toml", directory.FullName),
    $$"""
    [project]
    name = "pyright-generated-{{packageName}}-stubs"
    version = "{{packageVersion}}"
    description = "Unofficial type stubs of {{packageName}} generated by pyright."
    authors = [
        { name = "yueyinqiu", email = "yueyinqiu@outlook.com" }
    ]
    dependencies = []

    [build-system]
    requires = ["uv_build>=0.9.28,<0.10.0"]
    build-backend = "uv_build"

    [tool.uv.build-backend]
    module-name = "{{packageName}}-stubs"
    """);
    
static void CopyDirectory(DirectoryInfo source, DirectoryInfo target)
{
    target.Create();
    foreach (FileInfo file in source.GetFiles())
        file.CopyTo(Path.GetFullPath(file.Name, target.FullName), true);
    foreach (DirectoryInfo sub in source.GetDirectories())
        CopyDirectory(sub, new DirectoryInfo(Path.GetFullPath(sub.Name, target.FullName)));
}

Console.WriteLine("Copying type stubs...");
var module = new DirectoryInfo(Path.Join(directory.FullName, "src", $"{packageName}-stubs"));
CopyDirectory(generatedStubs, module);
await File.WriteAllTextAsync(Path.GetFullPath("py.typed", module.FullName), "");

Console.WriteLine("Building...");
await uv.WithArguments(["build"]).ExecuteAsync();

Console.WriteLine("Publishing...");
await uv.WithArguments(["publish"]).ExecuteAsync();
