name: Run

on:
    workflow_dispatch:

jobs:
    publish:
        runs-on: ubuntu-latest
        permissions:
            contents: read
        steps:
            - uses: actions/checkout@v6.0.2
            - uses: actions/setup-dotnet@v5.2.0
            - uses: astral-sh/setup-uv@v8.1.0
            - run: dotnet run script.cs
              env:
                UV_PUBLISH_TOKEN: ${{ secrets.UV_PUBLISH_TOKEN }}
              