name: Run

on:
    workflow_dispatch:

jobs:
    publish:
        runs-on: ubuntu-latest
      
        permissions:
            contents: read

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup dotnet
              uses: actions/setup-dotnet@v4

            - name: Setup uv
              uses: astral-sh/setup-uv@v5

            - name: Run script
              env:
                UV_PUBLISH_TOKEN: ${{ secrets.UV_PUBLISH_TOKEN }}
              run: dotnet run script.cs